services:
  - type: web
    name: l3-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      chmod +x start.sh
    startCommand: ./start.sh
    postdeploy: |
      python manage.py migrate --noinput
      python manage.py setup_admin
      python manage.py update_exam_structure
      python manage.py populate_course_materials
      python manage.py populate_video_content
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_XFQfLWR4b1du@ep-floral-union-a8h4usda-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DEBUG
        value: false
      - key: DATABASE_SSL_REQUIRE
        value: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin1
      - key: DJANGO_SUPERUSER_EMAIL
        value: bendarnoufel@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin1234
