# Generated by Django 5.2.5 on 2025-08-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('color', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('isil', 'ISIL'), ('acad', 'ACAD')], max_length=8)),
                ('semester', models.CharField(choices=[('s5', 'S5'), ('s6', 'S6')], max_length=8)),
            ],
            options={
                'ordering': ['specialization', 'semester', 'name'],
                'unique_together': {('name', 'specialization', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ExamResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('isil', 'ISIL'), ('acad', 'ACAD')], max_length=8)),
                ('url', models.URLField()),
                ('color', models.CharField(blank=True, help_text="Tailwind gradient classes, e.g. 'from-blue-500 to-indigo-500'", max_length=64)),
            ],
            options={
                'ordering': ['specialization', 'name'],
                'unique_together': {('name', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_playlists', to='content.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('s5', 'S5'), ('s6', 'S6')], max_length=8)),
                ('specialization', models.CharField(choices=[('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16)),
                ('url', models.URLField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='content.academicyear')),
            ],
            options={
                'ordering': ['-academic_year__start_year', 'semester', 'specialization'],
                'unique_together': {('academic_year', 'semester', 'specialization')},
            },
        ),
    ]
