# Generated by Django 5.2.5 on 2025-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_initial_data'),
        ('content', '0002_summaryresource_course_examresource_videoplaylist_and_more'),
    ]

    operations = [
    ]
