# Generated by Django 5.2.5 on 2025-08-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_merge_20250825_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresource',
            name='color',
        ),
        migrations.RemoveField(
            model_name='summaryresource',
            name='color',
        ),
    ]
