# Generated by Django 5.2.5 on 2025-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_migrate_and_remove_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedrivelink',
            name='specialization',
            field=models.CharField(choices=[('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
        migrations.AlterField(
            model_name='examresource',
            name='specialization',
            field=models.CharField(choices=[('isil', 'ISIL'), ('acad', 'ACAD')], max_length=16),
        ),
    ]
