# Generated by Django 5.2.5 on 2025-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_isil_c_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
        migrations.AlterField(
            model_name='examresource',
            name='specialization',
            field=models.CharField(choices=[('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
    ]
