# Generated by Django 5.2.4 on 2025-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_update_specialization_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['specialization', 'semester', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which courses should appear'),
        ),
    ]
