# Generated by Django 5.2.4 on 2025-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_course_options_course_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('acad', 'ACAD'), ('isil', 'ISIL'), ('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
    ]
