# Generated by Django 5.2.4 on 2025-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_course_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresource',
            options={'ordering': ['specialization', 'semester', 'display_order', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='examresource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresource',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which exams should appear'),
        ),
        migrations.AddField(
            model_name='examresource',
            name='semester',
            field=models.CharField(choices=[('s5', 'S5'), ('s6', 'S6')], default='s5', max_length=8),
        ),
        migrations.AlterField(
            model_name='examresource',
            name='specialization',
            field=models.CharField(choices=[('acad', 'ACAD'), ('isil', 'ISIL'), ('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='examresource',
            unique_together={('name', 'specialization', 'semester')},
        ),
    ]
