# Generated by Django 5.2.4 on 2025-08-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_examresource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresource',
            options={'ordering': ['specialization', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='examresource',
            unique_together={('name', 'specialization')},
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('isil_a', 'ISIL A'), ('isil_b', 'ISIL B'), ('isil_c', 'ISIL C'), ('acad_a', 'ACAD A'), ('acad_b', 'ACAD B'), ('acad_c', 'ACAD C')], max_length=16),
        ),
        migrations.AlterField(
            model_name='examresource',
            name='specialization',
            field=models.CharField(choices=[('isil', 'ISIL'), ('acad', 'ACAD')], max_length=16),
        ),
        migrations.RemoveField(
            model_name='examresource',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='examresource',
            name='semester',
        ),
    ]
