# Generated by Django 5.2.4 on 2025-08-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_examresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('isil', 'ISIL'), ('acad', 'ACAD')], max_length=16),
        ),
    ]
