# Generated by Django 5.2.4 on 2025-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_course_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresource',
            options={'ordering': ['specialization', 'semester', 'name']},
        ),
        migrations.AddField(
            model_name='examresource',
            name='semester',
            field=models.CharField(choices=[('s5', 'S5'), ('s6', 'S6')], default='s5', max_length=8),
        ),
    ]
